config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "application#index"
  get "/logout", to: "pognito#logout"
  get "/login", to: "pognito#login"

  namespace :dashboard do
    root "application#index"

    get "/profile", to: "user#index"

    resources :projects, only: [:index, :show, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :first_name, :last_name, :email, :phone

  validates :uuid, uniqueness: true, presence: true
  validates :hs_contact_id, :pl_client_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PognitoConcern

  def index
    redirect_to dashboard_root_path if pognito.tokens?
  end
end

app/controllers/concerns/pognito_concern.rb
# frozen_string_literal: true

module PognitoConcern
  extend ActiveSupport::Concern

  private
    def authenticate_user
      return if pognito.tokens? && current_user

      redirect_to_sign_in
    end

    def pognito
      @pognito ||= Pognito::Cognito.client(storage: session)
    end

    def current_user
      @current_user ||= find_or_create_user
    end

    def find_or_create_user
      result = UserServices::UpdateInfo.call(
        object: User.find_or_initialize_by(uuid: pognito.user["sub"]),
        params: pognito.user
      )

      flash[:alert] = result.errors unless result.success?

      result.user
    end

    def redirect_to_sign_in
      pognito.after_sign_in_path(request.url)

      redirect_to Pognito::Config.sign_in_url, allow_other_host: true
    end

    def redirect_to_sign_out
      pognito.sign_out

      redirect_to Pognito::Config.sign_out_url, allow_other_host: true
    end
end

app/controllers/dashboard/application_controller.rb
module Dashboard
  class ApplicationController < ApplicationController
    before_action :authenticate_user

    def index
      render template: "dashboard/index"
    end

    private
      def render(options={}, extra_options={}, &block)
        options[:locals] ||= {}
        options[:locals][:current_user] = current_user

        super
      end
  end
end

app/controllers/dashboard/projects_controller.rb
module Dashboard
  class ProjectsController < ApplicationController
    def index
      contact = hubspot.get_contact(id: current_user.hs_contact_id, associations: :deal)
      deals = contact.deal_ids.map { |id| hubspot.get_deal(id:) }

      render locals: { deals: }
    end

    def show
      contact = hubspot.get_contact_files(id: current_user.hs_contact_id, attributes: [:file1, :file2])
      deal = hubspot.get_deal_files(id: params[:id])

      quote_ids = hubspot.get_deal(id: params[:id], associations: :quote).quote_ids || []
      quotes = quote_ids.map { |id| hubspot.get_quote(id:, attributes: [:reference, :download_url]) }

      invoices = Crm::Pennylane.new.get_invoices_by_client_id(current_user.pl_client_id)

      render locals: { contact:, deal:, quotes:, invoices: }
    end

    def update
      result = Crm::HubspotServices::UploadDocuments.call(params: project_params)

      redirect_to dashboard_project_path(id: params[:id]) if result.success?
    end

    private
      def project_params
        params.require(:project).permit(:deal_id, :impot_file, :mairie_file, :contract_file).merge(deal_id: params[:id])
      end

      def hubspot
        @hubspot ||= Crm::Hubspot.new
      end
  end
end

app/controllers/dashboard/user_controller.rb
module Dashboard
  class UserController < ApplicationController
    def index
    end
  end
end

app/controllers/pognito_controller.rb
class PognitoController < ApplicationController
  include PognitoConcern

  def login
    if params[:code]
      pognito.store_tokens(params[:code])

      return redirect_to_after_sign_in
    end

    return redirect_to_sign_in unless pognito.tokens?

    redirect_to_after_sign_in
  end

  def logout
    redirect_to_sign_out
  end

  private
    def redirect_to_after_sign_in
      redirect_to pognito.after_sign_in_path || dashboard_root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/application/index.html.erb
<div class=wrapper>
  <div class="head">
    Env: <%= ENV["RAILS_ENV"] %>
  </div>
  <div data-turbo-prefetch="false">
    <a class="button" href="/login">Login</a>
  </div>
</div>
<style>
  .wrapper {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 10px;
  }

  body {
    background-color: #f0f0f0;
    font-family: sans-serif;
  }

  .head {
    background-color: #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .button {
    background-color: #482882;
    border: 2px solid #ffbc00;
    border-radius: 8px;
    color: white;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    margin-top: 10px;
    justify-content: center;
  }
</style>

app/views/dashboard/index.html.erb
<div class=wrapper>
  <div class="head">
    Env: <%= ENV["RAILS_ENV"] %>
  </div>
  <div class="content">
    <h2>Hey<%= current_user ? " #{current_user.first_name} " : "" %>!</h2>
  </div>
  <div data-turbo-prefetch="false">
    <%= link_to "Go to user page", dashboard_profile_path, class: "button" %>
    <%= link_to "Go to projects page", dashboard_projects_path, class: "button" %>
    <%= link_to "Logout", logout_path, class: "button" %>
  </div>
</div>
<style>
  .wrapper {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 10px;
  }

  body {
    background-color: #f0f0f0;
    font-family: sans-serif;
  }

  .head {
    background-color: #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .content {
    background-color: #fff;
    border: 2px solid #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .button {
    background-color: #482882;
    border: 2px solid #ffbc00;
    border-radius: 8px;
    color: white;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    margin-top: 10px;
    justify-content: center;
  }
</style>

app/views/dashboard/projects/index.html.erb
<div class="w-1/2 mx-auto border p-10">
  <div class="text-lg font-bold mb-10">Projects</div>
  <% deals.each do |deal| %>
    <div>
      <%= link_to deal.name, dashboard_project_path(deal.id), class: "underline" %>
    </div>
  <% end %>
</div>

app/views/dashboard/projects/show.html.erb
<div class="w-1/2 mx-auto">
  <div class="text-lg font-bold mb-10">
    <%= link_to "Back to projects", dashboard_projects_path, class: "underline" %>
  </div>
  <div class="border p-10">
    <div class="text-lg font-bold mb-10">Project info</div>
    <ul>
      <li>Name: <%= deal.name %></li>
      <li>Related quotes:
        <% quotes.each do |quote| %>
          <%= link_to quote.reference, quote.download_url, target: :_blank, class: "underline" %>
            <% end %>
      </li>
      <li>Related invoices:
        <% invoices.each do |invoice| %>
          <%= link_to invoice[:invoice_number], invoice[:file_url], target: :_blank, class: "underline" %>
            <% end %>
      </li>
      <% [:file1, :file2].each do |attr| %>
        <li>
          <%= attr %>:
            <% contact.send(attr).each do |file| %>
              <%= link_to file.name, file.url, target: :_blank, class: "underline" %>,
                <% end %>
        </li>
        <% end %>

          <% [:impot_file, :mairie_file, :contract_file].each do |attr| %>
            <li>
              <%= attr %>:
                <% deal.send(attr).each do |file| %>
                  <%= link_to file.name, file.url, target: :_blank, class: "underline" %>,
                    <% end %>
            </li>
            <% end %>
    </ul>
  </div>
  <div class="mt-10 border p-10">
    <div class="text-lg font-bold mb-10">Upload file to related deal</div>
    <%= form_with scope: :project, url: dashboard_project_path(deal.id), method: :put do |f| %>
      <div class="mb-6">
        <%= f.label :impot_file %>
        <%= f.file_field :impot_file %>
      </div>
      <div class="mb-6">
        <%= f.label :mairie_file %>
        <%= f.file_field :mairie_file %>
      </div>
      <div class="mb-6">
        <%= f.label :contract_file %>
        <%= f.file_field :contract_file %>
      </div>

      <%= f.submit class: "btn btn-blue" %>
    <% end %>
  </div>
</div>

app/views/dashboard/user/index.html.erb
<div class=wrapper>
  <div class="head">
    Env: <%= ENV["RAILS_ENV"] %>
  </div>
  <div class="content">
    <h2>Logged as: <%= "#{current_user.first_name} #{current_user.last_name}" %></h2>
    <ul>
      <li>Email: <%= current_user.email %></li>
      <li>User ID: <%= current_user.uuid %></li>
      <li>Hubspot contact ID: <%= current_user.hs_contact_id %></li>
      <li>Pennylane client_id ID: <%= current_user.pl_client_id %></li>
    </ul>
  </div>
  <div>
    <a class="button" href="/logout">Logout</a>
  </div>
</div>
<style>
  .wrapper {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 10px;
  }

  body {
    background-color: #f0f0f0;
    font-family: sans-serif;
  }

  .head {
    background-color: #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .content {
    background-color: #fff;
    border: 2px solid #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  li {
    list-style-type: none;
    margin: 5px 0;
  }

  .button {
    background-color: #482882;
    border: 2px solid #ffbc00;
    border-radius: 8px;
    color: white;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    margin-top: 10px;
    justify-content: center;
  }
</style>

app/views/index/index.html.erb
<div class=wrapper>
  <div class="head">
    Env: <%= ENV["RAILS_ENV"] %>
  </div>
  <div class="content">
    <h2>Hey<%= current_user ? " #{current_user[:username]} " : ""%>!</h2>
  </div>
  <div>
    <% if current_user %>
      <a class="button" href="/user">Go to user page</a>
      <a class="button" href="/logout">Logout</a>
    <% else %>
      <a class="button" href="/login">Login</a>
    <% end %>
  </div>
</div>
<style>
  .wrapper {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 10px;
  }

  body {
    background-color: #f0f0f0;
    font-family: sans-serif;
  }

  .head {
    background-color: #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .content {
    background-color: #fff;
    border: 2px solid #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .button {
    background-color: #482882;
    border: 2px solid #ffbc00;
    border-radius: 8px;
    color: white;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    margin-top: 10px;
    justify-content: center;
  }
</style>

app/views/index/user.html.erb
<div class=wrapper>
  <div class="head">
    Env: <%= ENV["RAILS_ENV"] %>
  </div>
  <div class="content">
    <h2>Logged as: <%= current_user[:username] %></h2>
    <ul>
      <Li>Email: <%= current_user[:email] %></li>
      <Li>User ID: <%= current_user[:sub] %></li>
      <li>Document: <%= link_to @document.name, @document.url, target: :_blank, class: "underline" %></li>
    </ul>
  </div>
  <div>
    <a class="button" href="/logout">Logout</a>
  </div>
</div>
<style>
  .wrapper {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 10px;
  }

  body {
    background-color: #f0f0f0;
    font-family: sans-serif;
  }

  .head {
    background-color: #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  .content {
    background-color: #fff;
    border: 2px solid #ffbc00;
    color: #482882;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
  }

  li {
    list-style-type: none;
    margin: 5px 0;
  }

  .button {
    background-color: #482882;
    border: 2px solid #ffbc00;
    border-radius: 8px;
    color: white;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    font-size: 16px;
    cursor: pointer;
    display: flex;
    margin-top: 10px;
    justify-content: center;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pognito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>

    <%= turbo_frame_tag "flash" do %>
      <%= render "shared/flash" %>
    <% end %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <div data-controller="flash" data-key="<%= key %>" class="
        group fixed top-24 right-5 z-[100] flex max-w-sm items-center rounded-lg
        py-3 px-5 data-[key=alert]:bg-[#DE475E] data-[key=notice]:bg-[#00D296]
      ">
      <div class="mr-4 text-sm font-semibold group-data-[key=alert]:text-white">
        <%= simple_format(value.is_a?(Array) ? value.join("\n") : value) %>
      </div>

      <button type="button" data-action="flash#dismiss" class="flex items-center">
        <i class="fa-solid fa-xmark hover:opacity-80 group-data-[key=alert]:text-white"></i>
      </button>
    </div>
  <% end %>
<% end %>